name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore
      run: dotnet restore TonSdk.NET.sln
    
    - name: Build
      run: dotnet build TonSdk.NET.sln --no-restore --configuration Release
    
    - name: Test
      run: dotnet test TonSdk.NET.sln --no-build --configuration Release

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore
      run: dotnet restore TonSdk.NET.sln
    
    - name: Build
      run: dotnet build TonSdk.NET.sln --no-restore --configuration Release
    
    - name: Pack Core
      run: dotnet pack TonSdk.Core/src/TonSdk.Core.csproj --no-build --configuration Release --output ./artifacts
    
    - name: Pack Adnl
      run: dotnet pack TonSdk.Adnl/src/TonSdk.Adnl.csproj --no-build --configuration Release --output ./artifacts
    
    - name: Pack Client
      run: dotnet pack TonSdk.Client/src/TonSdk.Client.csproj --no-build --configuration Release --output ./artifacts
    
    - name: Pack Contracts
      run: dotnet pack TonSdk.Contracts/src/TonSdk.Contracts.csproj --no-build --configuration Release --output ./artifacts
    
    - name: Pack Connect
      run: dotnet pack TonSDK.Connect/TonSdk.Connect.csproj --no-build --configuration Release --output ./artifacts
    
    - name: Pack DeFi
      run: dotnet pack TonSdk.DeFi/TonSdk.DeFi.csproj --no-build --configuration Release --output ./artifacts
    
    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

